pkpdapp-team/pkpdapp

CONTRIBUTING.md, README.md
This is the first step towards contribution guidelines. There are no guidelines in there yet, but at least an explanation of how the various apps in the PKPDApp will integrate.
Just have a look for typos and whether the intended structure makes sense to you
=> Contribution markdown

.gitignore, README.md, pkpdapp/pkpdapp/settings.py, pkpdapp/pkpdapp/templates/base.html, pkpdapp/pkpdapp/templates/registration/logged_out.html, pkpdapp/pkpdapp/templates/registration/login.html, pkpdapp/pkpdapp/templates/registration/password_reset_complete.html, pkpdapp/pkpdapp/templates/registration/password_reset_confirm.html, pkpdapp/pkpdapp/templates/registration/password_reset_done.html, pkpdapp/pkpdapp/templates/registration/password_reset_email.html, pkpdapp/pkpdapp/templates/registration/password_reset_form.html, pkpdapp/pkpdapp/tests/test_views.py, pkpdapp/pkpdapp/urls.py
Fixes #21 
I didn't link the email sending to an actual email server, so this doesn't really work atm, just prints the email out to the console.
=> Issue 21 auth

.coveragerc, pkpdapp/pkpdapp/tests/test_urls.py, pkpdapp/simulate/views.py
Closes #27 .
Just added simple URL tests for the pkpdapp.
=> I27 url tests

Dockerfile, README.md, nginx.default, pkpdapp/pkpdapp/settings.py, requirements.txt, start-server.sh
Fixes #33 
Added a Dockerfile that uses gunicorn and nginx to serve the webapp, for eventual deployment (see #23)
Note: change static root dir to `BASE_DIR/static` (was `BASE_DIR/staticfiles`)
=> Issue 33 dockerfile

Dockerfile, README.md, heroku.yml, nginx.default.template, pkpdapp/pkpdapp/settings.py, start-server.sh
Fixes #23
App is currently live on: https://pkpdapp.herokuapp.com/
=> Issue 23 deploy

pkpdapp/pkpdapp/templates/base/head.html
=> #43 show logged in user in header

Dockerfile
=> #88 add git to list of installed software in dockerfile

Dockerfile
trying to upgrade docker image to python 3.8
=> Issue 94 heroku

README.md
=> Update README.md to include test details

pkpdapp/pkpdapp/migrations/0005_initial_datasets.py, pkpdapp/pkpdapp/migrations/0006_initial_pkpd_models.py, pkpdapp/pkpdapp/models/biomarker.py, pkpdapp/pkpdapp/templates/project_detail.html, pkpdapp/simulate/apps.py, pkpdapp/simulate/dash_apps/simulation.py, pkpdapp/simulate/templates/simulate/simulation.html, pkpdapp/simulate/templatetags/simulate_extras.py, pkpdapp/simulate/tests/test_dash_apps_simulation.py, pkpdapp/simulate/tests/test_views.py, pkpdapp/simulate/views.py, setup.py
Fixes #94 
I've also restructured the simulation dash app so that it can take mulitple models and datasets, and you can choose which biomarker you wish to display
=> Issue 94 simulate

pkpdapp/pkpdapp/dash_apps/simulation.py, pkpdapp/pkpdapp/erlotinib/_mechanistic_models.py, pkpdapp/pkpdapp/migrations/0006_initial_pkpd_models.py
Fixes #116 
- plots concentrations instead of amounts in simluation app
- adds axis labels to simulation app
=> Issue 116 plot concentration

pkpdapp/pkpdapp/api/serializers.py, pkpdapp/pkpdapp/migrations/0001_initial.py, pkpdapp/pkpdapp/migrations/0005_initial_datasets.py, pkpdapp/pkpdapp/migrations/0007_initial_units.py, pkpdapp/pkpdapp/models/__init__.py, pkpdapp/pkpdapp/models/biomarker_type.py, pkpdapp/pkpdapp/models/dose.py, pkpdapp/pkpdapp/models/protocol.py, pkpdapp/pkpdapp/models/subject.py, pkpdapp/pkpdapp/models/units.py, pkpdapp/pkpdapp/tests/test_models/test_biomarker.py, pkpdapp/pkpdapp/tests/test_models/test_biomarker_type.py, pkpdapp/pkpdapp/tests/test_models/test_mechanistic_model.py, pkpdapp/pkpdapp/tests/test_models/test_other.py, pkpdapp/pkpdapp/tests/test_models/test_protocol.py, pkpdapp/pkpdapp/tests/test_models/test_subject.py
=> Issue 142 units

frontend/src/App.js, frontend/src/features/forms/FormComponents.js, frontend/src/features/pdModels/PdDetail.js
=> #169 add new form file field

frontend/package.json, frontend/src/Api.js, frontend/src/features/datasets/DatasetDetail.js, frontend/src/features/datasets/datasetsSlice.js, frontend/src/features/forms/FormComponents.js, frontend/src/features/pdModels/PdDetail.js, frontend/src/features/pdModels/pdModelsSlice.js, frontend/yarn.lock, pkpdapp/pkpdapp/api/serializers.py, pkpdapp/pkpdapp/api/views.py, pkpdapp/pkpdapp/models/mechanistic_model.py, pkpdapp/pkpdapp/models/units.py, pkpdapp/pkpdapp/tests/test_views/test_dataset.py
=> Issue 168 create dataset

frontend/package.json, frontend/src/App.js, frontend/src/Login.js, frontend/src/features/datasets/DatasetDetail.js, frontend/src/features/datasets/Datasets.js, frontend/src/features/forms/ComponentForm.js, frontend/src/features/forms/FormComponents.js, frontend/src/features/menu/AvatarListItem.js, frontend/src/features/menu/ExpandableListItem.js, frontend/src/features/menu/ProjectMenu.js, frontend/src/features/modelling/Chart.js, frontend/src/features/modelling/Modelling.js, frontend/src/features/pdModels/PdDetail.js, frontend/src/features/pdModels/PdModels.js, frontend/src/features/pkModels/PkDetail.js, frontend/src/features/pkModels/PkModels.js, frontend/src/features/projects/ListOfProjects.js, frontend/src/features/projects/ProjectDetail.js, frontend/src/features/projects/Projects.js, frontend/src/features/projects/unitsSlice.js, frontend/src/features/protocols/ProtocolDetail.js, frontend/src/features/protocols/Protocols.js, frontend/src/features/protocols/protocolsSlice.js, frontend/yarn.lock, pkpdapp/pkpdapp/api/serializers.py, pkpdapp/pkpdapp/models/mechanistic_model.py, pkpdapp/pkpdapp/tests/test_models/test_mechanistic_model.py
=> Issue 175 vis models

frontend/src/Api.js, frontend/src/App.js, frontend/src/features/forms/FormComponents.js, frontend/src/features/login/ActivateUser.js, frontend/src/features/login/ActivateUserSuccess.js, frontend/src/features/login/Login.js, frontend/src/features/login/Register.js, frontend/src/features/login/RegisterSuccess.js, frontend/src/features/login/ResetPassword.js, frontend/src/features/login/ResetPasswordRequest.js, frontend/src/features/login/ResetPasswordRequestSuccess.js, frontend/src/features/login/ResetPasswordSuccess.js, frontend/src/features/login/Success.js, frontend/src/features/projects/ProjectDetail.js, pkpdapp/pkpdapp/models/profile.py, pkpdapp/pkpdapp/settings.py, setup.py
=> Issue 180 login

README.md, pkpdapp/pkpdapp/settings.py
=> Issue 186 dockerfile

frontend/src/features/login/Login.js, frontend/src/features/login/Register.js, frontend/src/features/menu/ProjectMenu.js
=> #197 hide passwords

frontend/src/features/datasets/DatasetDetail.js, frontend/src/features/datasets/datasetsSlice.js, frontend/src/features/pdModels/PdDetail.js, frontend/src/features/pdModels/pdModelsSlice.js, frontend/src/features/pkModels/PkDetail.js, frontend/src/features/pkModels/pkModelsSlice.js, frontend/src/features/protocols/ProtocolDetail.js, frontend/src/features/protocols/protocolsSlice.js, pkpdapp/pkpdapp/tests/test_models/test_dataset.py, pkpdapp/pkpdapp/tests/test_models/test_other.py
=> I206 delete

frontend/src/features/datasets/BiomarkerTypeSubform.js, frontend/src/features/datasets/DatasetDetail.js, frontend/src/features/forms/FormComponents.js, frontend/src/features/menu/AvatarListItem.js, frontend/src/features/modelling/Chart.js, frontend/src/features/projects/ProjectDetail.js, frontend/src/features/projects/Projects.js, frontend/src/features/projects/projectsSlice.js, frontend/src/features/variables/OutputSubform.js, pkpdapp/pkpdapp/api/views.py, pkpdapp/pkpdapp/migrations/0001_initial.py, pkpdapp/pkpdapp/models/biomarker_type.py, pkpdapp/pkpdapp/models/protocol.py, pkpdapp/pkpdapp/models/variable.py
Fixes #200 
also can now add and delete projects and they are filtered by user
=> I200 second yaxis

.dockerignore, .env, README.md, docker-compose.yml, frontend/src/app/store.js, frontend/src/features/inference/Inference.js, frontend/src/features/inference/InferenceDetail.js, frontend/src/features/inference/chainSlice.js, frontend/src/features/inference/inferenceSlice.js, frontend/src/features/projects/ProjectDetail.js, pkpdapp/pkpdapp/__init__.py, pkpdapp/pkpdapp/api/serializers/inference.py, pkpdapp/pkpdapp/api/views/filters.py, pkpdapp/pkpdapp/celery.py, pkpdapp/pkpdapp/models/inference.py, pkpdapp/pkpdapp/models/inference_results.py, pkpdapp/pkpdapp/settings.py, pkpdapp/pkpdapp/tasks.py, pkpdapp/pkpdapp/tests/test_models/test_inference.py, pkpdapp/pkpdapp/tests/test_views/test_inference.py, requirements.txt, start-server.sh
=> I230 celery

frontend/src/features/inference/Inference.js, frontend/src/features/inference/InferenceChart.js, frontend/src/features/inference/InferenceDetail.js, frontend/src/features/inference/Inferences.js, frontend/src/features/inference/inferenceSlice.js, frontend/src/features/pdModels/pdModelsSlice.js, frontend/src/features/pkModels/pkModelsSlice.js, frontend/src/features/variables/variablesSlice.js, frontend/yarn.lock
=> I236 yarn upgrade

frontend/package.json, frontend/yarn.lock
=> #236 further security fixes

frontend/src/features/inference/InferenceChart.js, frontend/src/features/inference/InferenceChartOptimisationResults.js, frontend/src/features/inference/InferenceChartSamplingResults.js, frontend/src/features/inference/InferenceChartTraces.js, frontend/src/features/inference/InferenceDetail.js, frontend/src/features/inference/chainSlice.js, frontend/src/features/inference/inferenceSlice.js, pkpdapp/pkpdapp/api/serializers/inference.py, pkpdapp/pkpdapp/models/inference.py, pkpdapp/pkpdapp/models/inference_mixin.py, pkpdapp/pkpdapp/settings.py, pkpdapp/pkpdapp/tasks.py, pkpdapp/pkpdapp/tests/test_models/test_inference_mixin.py
=> #243 run inference in frontend

LICENSE.md, frontend/src/features/inference/InferenceDetail.js, pkpdapp/pkpdapp/models/inference_mixin.py, pkpdapp/pkpdapp/models/myokit_pints_forward_model.py, pkpdapp/pkpdapp/tests/test_models/test_myokit_pints_forward_model.py, requirements.txt
=> #247 allow concentrations for inference

frontend/src/Api.js, frontend/src/App.js, frontend/src/app/store.js, frontend/src/features/datasets/DatasetDetail.js, frontend/src/features/inference/InferenceDetail.js, frontend/src/features/inference/algorithmsSlice.js, frontend/src/features/inference/inferenceSlice.js, frontend/src/features/login/Login.js, frontend/src/features/login/RequireLogin.jsx, frontend/src/features/login/loginSlice.js, frontend/src/features/modelling/Modelling.js, frontend/src/features/pdModels/PdDetail.js, frontend/src/features/pdModels/pdModelsSlice.js, frontend/src/features/pkModels/PkDetail.js, frontend/src/features/pkModels/pkModelsSlice.js, frontend/src/features/projects/ProjectDetail.js, frontend/src/features/projects/projectsSlice.js, frontend/src/features/projects/unitsSlice.js, frontend/src/features/projects/usersSlice.js, frontend/src/features/protocols/ProtocolDetail.js, frontend/src/features/protocols/protocolsSlice.js, frontend/src/features/variables/variablesSlice.js, pkpdapp/pkpdapp/api/__init__.py, pkpdapp/pkpdapp/api/views/__init__.py, pkpdapp/pkpdapp/api/views/login.py, pkpdapp/pkpdapp/api/views/simulate.py, pkpdapp/pkpdapp/settings.py, pkpdapp/pkpdapp/urls.py
=> #270 swap to session based auth for frontend

frontend/src/features/datasets/biomarkerTypesSlice.js, frontend/src/features/datasets/datasetsSlice.js, frontend/src/features/inference/InferenceListDialog.js, frontend/src/features/modelling/Chart.js, frontend/src/features/modelling/Modelling.js, frontend/src/features/pdModels/PdDetail.js, frontend/src/features/pdModels/pdModelsSlice.js, frontend/src/features/pkModels/PkDetail.js, frontend/src/features/pkModels/pkModelsSlice.js, pkpdapp/pkpdapp/api/views/biomarker_type.py, pkpdapp/pkpdapp/api/views/inference.py, pkpdapp/pkpdapp/api/views/models.py, pkpdapp/pkpdapp/models/__init__.py, pkpdapp/pkpdapp/models/dataset.py, pkpdapp/pkpdapp/models/inference.py, pkpdapp/pkpdapp/models/inference_mixin.py, pkpdapp/pkpdapp/models/inference_results.py, pkpdapp/pkpdapp/models/myokit_model_mixin.py, pkpdapp/pkpdapp/tests/test_models/test_inference.py
=> I276set param from inference

.env, pkpdapp/pkpdapp/settings.py, requirements.txt
=> #278 add ldap, support searching with bind dn, as well as direct bind

frontend/src/features/projects/Projects.js, frontend/src/features/projects/projectsSlice.js
=> #284 fix create new project button

frontend/src/features/projects/ProjectDetail.js, frontend/src/features/projects/projectsSlice.js, pkpdapp/pkpdapp/api/serializers/biomarker_type.py, pkpdapp/pkpdapp/api/serializers/project.py, pkpdapp/pkpdapp/migrations/0001_initial.py, pkpdapp/pkpdapp/models/project.py
=> #291 fix user access add

pkpdapp/pkpdapp/models/dataset.py, pkpdapp/pkpdapp/tests/test_utils/test_data_parser.py, pkpdapp/pkpdapp/utils/data_parser.py
=> #295 fix data upload bugs, test data upload for more datasets

pkpdapp/pkpdapp/api/views/filters.py
=> #332 superuser only gets own projects via api

frontend-v2/src/app/api.ts, frontend-v2/src/features/projects/Project.tsx, frontend-v2/src/features/simulation/SimulationSliderView.tsx, frontend-v2/src/features/trial/Doses.tsx
=> #337 slider tooltip to bottom

frontend-v2/yarn.lock
Patch and minor version updates for frontend dependencies.
=> Upgrade dependencies

frontend-v2/src/components/DynamicTabs.tsx, frontend-v2/src/components/HelpButton.tsx, frontend-v2/src/features/drug/Drug.tsx, frontend-v2/src/features/login/login.tsx, frontend-v2/src/features/main/Sidebar.tsx, frontend-v2/src/features/main/mainSlice.ts, frontend-v2/src/features/model/MapVariablesTab.tsx, frontend-v2/src/features/model/Model.tsx, frontend-v2/src/features/model/PKPDModelTab.tsx, frontend-v2/src/features/model/VariableRow.tsx, frontend-v2/src/features/projects/Project.tsx, frontend-v2/src/features/projects/UserAccess.tsx, frontend-v2/src/features/simulation/SimulationPlotView.tsx, frontend-v2/src/features/simulation/Simulations.tsx
Clean up unused variables and React globals.
This should make the builds less noisy.
=> refactor(frontend): clean up frontend code

frontend-v2/src/features/drug/Drug.tsx, frontend-v2/src/features/model/ParameterRow.tsx, frontend-v2/src/features/projects/Project.tsx, frontend-v2/src/features/trial/Doses.tsx, frontend-v2/src/hooks/useInterval.ts
Replace `useEffect` hooks with a `useInterval` hook that sets a timeout.
=> refactor: useInterval hook for autosave

pkpdapp/pkpdapp/models/compound.py, pkpdapp/pkpdapp/tests/test_models/test_project.py
=> #364 copy compount type

frontend-v2/src/features/data/MapObservations.tsx
When the uploaded CSV doesn't have an observation unit column, allow the user to pick a unit from a list of units, then pick a compatible variable for the selected unit.
=> fix: handle missing observation units in the CSV

pkpdapp/pkpdapp/models/dataset.py, pkpdapp/pkpdapp/utils/data_parser.py
Map ADDL and II columns, in the CSV, to repeat doses in the model and simulations.
=> feat: handle additional doses from a data row

frontend-v2/src/features/data/PreviewData.tsx
Add a download option to the CSV preview step, before uploading a CSV and converting it to a dataset.
=> feat: download a dataset as a CSV

frontend-v2/src/features/data/Data.tsx
Break the Data view up into tabs, one for each subject group.
=> refactor: tabbed data view

frontend-v2/src/features/data/LoadData.tsx
Normalise the time column so that the uploaded header is always 'Time'.
=> refactor: normalise the Time column header

frontend-v2/package.json, frontend-v2/vite.config.ts, frontend-v2/yarn.lock
- tweak the Rollup manual chunks config to adjust output bundle sizes.
- remove some unused packages.
=> build(frontend): tweak build bundle sizes

frontend-v2/src/features/data/LoadDataStepper.tsx, frontend-v2/src/features/data/PreviewData.tsx, frontend-v2/src/features/data/normaliseDataHeaders.ts
Validate Time values as numbers. Ignore any row with an invalid Time value.
=> feat(frontend): validate Time column values

frontend-v2/src/features/data/ProtocolDataGrid.tsx
Reduce the columns shown during data stratification to just categorical covariates plus dose amounts.
=> refactor(frontend): refactor data stratification columns

frontend-v2/src/features/data/LoadDataStepper.tsx
Refactor the data stepper as a non-linear stepper. Step labels are clickable, and steps can be followed in any order.
=> refactor(frontend): interactive data stepper labels

pkpdapp/pkpdapp/utils/data_parser.py
Just use the default of 0.0833
=> bug: simplify default infusion time in parser

pkpdapp/pkpdapp/migrations/0007_initial_units.py, pkpdapp/pkpdapp/tests/test_models/test_unit.py, start-server.sh
Adds some more concentration units:. g/L and mol/L with the following suffixes p, n, µ, m for g and mol and the following suffixes for L, m (20 combination).
=> feat: add more concentration units

frontend-v2/src/features/main/Sidebar.tsx
Change the validation for trial doses so that each protocol must have at least one dose, and the dose amount must not be zero.
=> refactor(frontend): validate trial dose amounts

frontend-v2/src/features/data/DosingProtocols.tsx, frontend-v2/src/features/data/ProtocolDataGrid.tsx, frontend-v2/src/features/data/Stratification.tsx, frontend-v2/src/features/data/normaliseDataHeaders.ts, pkpdapp/pkpdapp/models/dataset.py, pkpdapp/pkpdapp/tests/test_utils/test_data_parser.py, pkpdapp/pkpdapp/utils/data_parser.py
- rename ROUTE as ADMINISTRATION_NAME in the data parser.
- add 'Administration Name' as a column type in the CSV uploader.
=> refactor: rename ROUTE as ADMINISTRATION_NAME

frontend-v2/package.json, frontend-v2/src/features/simulation/SimulationPlotView.tsx, frontend-v2/src/vite-env.d.ts, frontend-v2/vite.config.ts, frontend-v2/yarn.lock
Import Plotly from `plotly.js-basic-dist-min` but load types from `@types/plotly.js`.
=> build(frontend): refactor Plotly imports

frontend-v2/src/features/trial/Protocols.tsx
Older protocols, created on the main branch, won't have the new `mapped_qname` field. In that case, set `protocol.mapped_qname` from `protocol.variables`, when we create a new protocol in the Trial Design tab.
=> fix(frontend): protocol mapped qname for legacy projects

frontend-v2/vite.config.ts
Use `loadEnv` to load the `.env` file dynamically at build time. Otherwise, `VITE_APP_GA_ID` isn't injected into the Docker build environment.
=> fix(frontend): Vite Google Analytics config

frontend-v2/src/features/data/ProtocolDataGrid.tsx, frontend-v2/src/features/data/SubjectGroupForm.tsx, frontend-v2/src/features/drug/Drug.tsx, frontend-v2/src/features/model/Model.tsx, frontend-v2/src/features/model/VariableRow.tsx, frontend-v2/src/features/projects/Projects.tsx, frontend-v2/src/features/simulation/useExportSimulation.ts
Fix some simple TypeScript errors.
=> fix(frontend): TypeScript errors

frontend-v2/src/app/backendApi.ts, frontend-v2/src/features/data/Data.tsx, frontend-v2/src/features/data/LoadDataStepper.tsx, pkpdapp/pkpdapp/api/serializers/dataset.py, pkpdapp/schema.yml
- update the `dataset/csv` API to accept a dataset name.
- send the filename as the dataset name when we upload CSV data.
=> feat: save the CSV filename as the dataset name

frontend-v2/src/features/data/Data.tsx
Display dosing protocols in order of dose time, in the Data tab.
=> refactor(frontend): sort protocols by dose time

frontend-v2/src/features/data/Stratification.tsx
Error during stratification if group dosing is inconsistent, so that the dataset can't be uploaded.
=> fix(frontend): make inconsistent group dosing an error

frontend-v2/src/features/data/LoadDataStepper.tsx, frontend-v2/src/features/data/Stratification.tsx
Error in upload when trying to ignore a column "AMT", which was still sent to the backend as an empty column named "AMT"
=> fix: ignored columns included in csv upload

frontend-v2/src/app/api.ts, frontend-v2/src/features/data/PreviewData.tsx, frontend-v2/src/features/main/Sidebar.tsx, frontend-v2/src/features/simulation/SimulationPlotView.tsx, frontend-v2/src/features/simulation/Simulations.tsx
A few small code errors that were flagged by CI.
=> fix(frontend): small bug fixes

frontend-v2/src/features/data/LoadData.tsx
=> PKPDX-11 PKPDX-13

frontend-v2/src/features/data/Data.tsx, frontend-v2/src/features/data/LoadData.tsx, frontend-v2/src/features/data/LoadDataStepper.tsx
=> PKPDX-12 Add 'Previous' and 'Cancel' buttons

frontend-v2/src/features/main/MainContent.tsx, frontend-v2/src/features/main/Sidebar.tsx, frontend-v2/src/features/main/mainSlice.ts, frontend-v2/src/features/secondary/SecondaryParameters.tsx, frontend-v2/src/features/secondary/ThresholdsTable.tsx, frontend-v2/src/features/secondary/TimeIntervalsTable.tsx
First pass at an interface for setting secondary parameters:
- add and remove time intervals.
- set thresholds for concentration variables.
=> feat(frontend): secondary parameters tab

frontend-v2/src/features/data/LoadDataStepper.tsx, frontend-v2/src/features/data/MapHeaders.tsx, frontend-v2/src/features/data/Notifications.tsx, frontend-v2/src/features/data/ProtocolDataGrid.tsx, frontend-v2/src/features/data/SetUnits.tsx, frontend-v2/src/features/data/Stratification.tsx, frontend-v2/src/features/data/SubjectGroupForm.tsx
[screencast-localhost_5173-2024_10_09-14_59_47.webm](https://github.com/user-attachments/assets/30d67a33-9880-46b2-af34-2d94f42a68eb)
=> PKPDX-16; PKPDX-17; PKPDX-18

frontend-v2/src/App.tsx, frontend-v2/src/contexts/SimulationContext.ts, frontend-v2/src/features/main/MainContent.tsx, frontend-v2/src/features/main/Sidebar.tsx, frontend-v2/src/features/main/mainSlice.ts, frontend-v2/src/features/results/Results.tsx, frontend-v2/src/features/results/VariableTable.tsx, frontend-v2/src/features/results/VariableTabs.tsx, frontend-v2/src/features/simulation/useSimulation.ts
A tabbed view for each subject group and selected concentration variable, showing minimum value, maximum value, area under the curve, and time above threshold by time interval.
=> feat(frontend): secondary parameters results tab

pkpdapp/pkpdapp/models/combined_model.py
Add units to Area Under Curve calculations for derived parameters.
=> fix(backend): add units to AUC calculations

frontend-v2/src/features/data/CreateDosingProtocols.tsx, frontend-v2/src/features/data/DosingProtocols.tsx, frontend-v2/src/features/data/LoadData.tsx, frontend-v2/src/features/data/MapDosing.tsx, frontend-v2/src/features/data/MapHeaders.tsx
Fix for Time Unit values not being updated when user selects time unit on Upload Data step
=> PKPDX-19; Fix Time Unit not being updated

frontend-v2/src/features/results/VariableTable.tsx
Account for curves with multiple doses, which may cross a threshold more than once, by recursively searching for threshold crossing points within an interval. The search ends when the start index of a search exits the current time interval.
=> refactor(frontend): iterate over thresholds for Results tables

frontend-v2/src/features/data/Data.tsx, frontend-v2/src/features/data/generateCSV.ts
make some edits to the generated csv to make it compatible with nonmem, and add a new button to allow users to download nonmem formatted datasets
=> feat: add nonmem csv download button

frontend-v2/src/features/data/CreateDosingProtocols.tsx, frontend-v2/src/features/data/Data.tsx, frontend-v2/src/features/data/MapObservations.tsx, frontend-v2/src/features/data/PreviewData.tsx, frontend-v2/src/shared/calculateTableHeights.ts
Updated styling for Preview Dataset view; Updated styling for Data main view when Dataset is saved
=> PKPDX-21 PKPDX-22

frontend-v2/src/App.css, frontend-v2/src/App.tsx, frontend-v2/src/components/DropdownButton.tsx, frontend-v2/src/components/SelectField.tsx, frontend-v2/src/components/UnitField.tsx, frontend-v2/src/features/main/MainContent.tsx, frontend-v2/src/features/main/Sidebar.tsx, frontend-v2/src/features/simulation/SimulationPlotView.tsx, frontend-v2/src/features/simulation/SimulationSliderView.tsx, frontend-v2/src/features/simulation/Simulations.tsx, frontend-v2/src/features/simulation/SimulationsSidePanel.tsx, frontend-v2/src/shared/calculateTableHeights.ts
=> PKPDX-27 - Simulations page

frontend-v2/src/App.tsx, frontend-v2/src/features/simulation/SimulationsSidePanel.tsx
=> Fix missing import;

frontend-v2/src/features/results/useParameters.tsx
Refactor `useParameters` to move some duplicated code into shared functions.
=> refactor(frontend): refactor useParameters hook

frontend-v2/src/features/results/Results.tsx, frontend-v2/src/features/results/ResultsTable.tsx, frontend-v2/src/features/results/columns.tsx, frontend-v2/src/features/results/useTableRows.ts, frontend-v2/src/features/results/utils.ts
Simplify and document the `ResultsTable` props.
=> refactor(frontend): ResultsTable API

frontend-v2/src/features/results/Results.tsx, frontend-v2/src/features/results/ResultsTab.tsx, frontend-v2/src/features/results/ResultsTable.tsx, frontend-v2/src/features/results/useTableRows.ts
Add tabs to the Results page, so that we can save multiple sets of results.
=> feat(frontend): tabbed Results page

frontend-v2/src/App.tsx, frontend-v2/src/features/results/Results.tsx, frontend-v2/src/features/results/ResultsTab.tsx, frontend-v2/src/features/results/ResultsTable.tsx
[results page.webm](https://github.com/user-attachments/assets/31a1ad04-8613-46b9-bf2b-9e42177f5b8a)
=> PKPDX-29 results page

frontend-v2/src/features/results/ResultsTab.tsx, frontend-v2/src/features/results/ResultsTable.tsx
[headers demo.webm](https://github.com/user-attachments/assets/ba63ad69-1d29-4b75-904c-91c602e1102f)
=> PKPDX-29 Add headers to results tables

frontend-v2/src/App.tsx, frontend-v2/src/features/model/secondary/TimeIntervalsTable.tsx, frontend-v2/src/features/results/useTableRows.ts
Store time interval units as objects with conversion factors, symbols, and unit IDs.
=> refactor(frontend): time interval units

frontend-v2/src/features/simulation/Simulations.tsx
Fix a couple of small TS errors in the `Simulations` component.
=> fix(frontend): TypeScript errors in Simulations

frontend-v2/src/features/results/useParameters.tsx
Normalise all Results times to hours, for the time being.
=> feat(frontend): normalise Results time units

frontend-v2/src/features/model/secondary/ThresholdsTable.tsx
Pull data-fetching logic out of the `ThresholdsTable` component and into custom hooks.
=> refactor(frontend): clean up ThresholdsTable

frontend-v2/src/features/results/useParameters.tsx
Add unit conversion to the Results parameters, so that each parameter is displayed in the units that were selected under Model > Secondary Parameters.
=> feat(frontend): display units for Results

frontend-v2/src/features/results/ResultsTab.tsx, frontend-v2/src/features/results/ResultsTable.tsx, frontend-v2/src/features/results/useParameters.tsx, frontend-v2/src/features/results/useTableRows.ts, frontend-v2/src/features/results/utils.ts
Choose the units for each results table, from dropdown menus of concentration untis and time units.
=> feat(frontend): customise Results table units

frontend-v2/src/features/results/ResultsTab.tsx, frontend-v2/src/features/simulation/SimulationPlotView.tsx, frontend-v2/src/features/simulation/Simulations.tsx, frontend-v2/src/features/simulation/SimulationsSidePanel.tsx
[autolayout.webm](https://github.com/user-attachments/assets/ffe56a09-6d2e-4b73-87ba-556850ff0e1f)
=> Fix no padding on results page; Add 'auto' layout when no/all options are selected

frontend-v2/src/components/FloatField.tsx, frontend-v2/src/components/IntegerField.tsx, frontend-v2/src/components/SelectField.tsx, frontend-v2/src/components/UnitField.tsx, frontend-v2/src/features/results/Results.tsx, frontend-v2/src/features/trial/Doses.tsx, frontend-v2/src/features/trial/Protocols.tsx
=> PKPDX-32 trial design changes

frontend-v2/src/features/results/useParameters.tsx
Invert unit conversion so that we calculate the conversion factor from simulation units to display units, rather then vice versa. Then multiply displayed values by the conversion factor rather than dividing. Move conversion functions into the module scope.
=> refactor(frontend): invert secondary parameter unit conversion

frontend-v2/src/features/simulation/SimulationPlotView.tsx, frontend-v2/src/features/simulation/config.ts, frontend-v2/src/features/simulation/utils.ts, frontend-v2/src/hooks/useDataset.ts
Break up simulation plots into smaller pieces, moving the config and plot utility functions into `features/simulation/config.js` and `features/simulation/utils.js` respectively.
=> refactor(frontend): refactor simulation plots

frontend-v2/src/features/simulation/SimulationPlotView.tsx, frontend-v2/src/features/simulation/utils.ts
Refactor the calculation of the Y ranges for plots so that they don't rely on global variables being updated as a side effect of an array map.
=> refactor(frontend): plot Y ranges

frontend-v2/src/features/simulation/SimulationPlotView.tsx, frontend-v2/src/features/simulation/utils.ts
Break up the code for `icLines` into smaller functions.
=> refactor(frontend): refactor iclines

frontend-v2/src/features/data/generateCSV.ts, frontend-v2/src/features/simulation/utils.ts
Fix a couple of CI code reliability warnings.
=> refactor(frontend): fix CI reliability warnings

frontend-v2/src/features/simulation/SimulationPlotView.tsx, frontend-v2/src/features/simulation/utils.ts
DRY up the code for generating plots. Rename some variables for consistency.
=> refactor(frontend): create simulation plots

frontend-v2/package.json
Patch and minor updates for frontend dependencies.
=> chore: version 2.0.1

frontend-v2/src/features/trial/DoseRow.tsx, frontend-v2/src/features/trial/Doses.tsx, frontend-v2/src/features/trial/Protocols.tsx, pkpdapp/pkpdapp/api/views/dose.py
Refactor Trial Design dose rows into a `DoseRow` component, which handles the values for a single dose in the `protocol.doses` array. Give each dose row its own form controller to handle input value changes.
- fixes #674.
https://github.com/user-attachments/assets/3ddbae03-0364-42a8-813f-f59361340ac6
=> refactor(frontend): trial design dose rows form

frontend-v2/src/features/simulation/Simulations.tsx
Fix the calculation of group plot visibility so that the 'Project' group is visible by default.
=> fix: project plots aren't visible by default

.github/workflows/frontend-build.yml, frontend-v2/package.json, frontend-v2/src/app/backendApi.ts, frontend-v2/src/reportWebVitals.ts, frontend-v2/yarn.lock
- major version updates for dev dependencies.
- use `yarn build` to test the build in CI.
- update the frontend OpenAPI client.
- track core web vitals in the console.
=> build(frontend): update dependencies

frontend-v2/src/features/model/PKPDModelTab.tsx
Changes to MUI `Grid` broke the layout of the PKPD Model tab.
=> fix(frontend): PKPD Model layout

frontend-v2/src/features/model/Model.tsx
- move Redux queries into a `useApiQueries` custom hook.
- declare default objects outside the main function body.
=> refactor(frontend): Model tab

frontend-v2/src/features/model/Model.tsx, frontend-v2/src/features/model/PKPDModelTab.tsx
Extract Model tab form state into a custom hook.
=> refactor(frontend): Model form state

frontend-v2/src/features/model/Model.tsx
Memoise the Model form submission fuctions with `useCallback`.
=> refactor(frontend): memoise Model form data

frontend-v2/src/app/hooks.ts
Fix a missing dependency warning in the `useFieldState` hook.
=> fix(frontend): missing dependency in useFieldState hook

frontend-v2/src/features/projects/Project.tsx
Fix a missing dependency warning for project edit mode state.
=> fix(frontend): fix project edit mode hook

frontend-v2/src/features/model/Model.tsx
- split Model into two components:
- Model: fetches API data and waits for loading to complete.
- TabbedModelForm: renders once data loading is complete.
- replace `values` with `defaultValues` in TabbedModelForm. Form state is set on initial load, and controlled by user input thereafter. This removes the form reset whenever `model` updates in the backend, which could cause flashes of stale state.
- remove the `DEFAULT_MODEL` constant. The combined model from the backend is now the initial source of truth for form state.
- closes #723.
=> refactor(frontend): make Model form uncontrolled

frontend-v2/src/components/DynamicTabs.tsx
Clean up an 'unexpected any' type error.
=> chore(frontend): clean up linter error

frontend-v2/src/App.css, frontend-v2/src/app/hooks.ts, frontend-v2/src/components/UnitField.tsx, frontend-v2/src/features/data/DosingProtocols.tsx, frontend-v2/src/features/help/Help.tsx, frontend-v2/src/features/main/MainContent.tsx, frontend-v2/src/features/main/Sidebar.tsx, frontend-v2/src/features/projects/Projects.tsx, frontend-v2/src/features/projects/UserAccess.tsx, frontend-v2/src/features/results/ResultsTab.tsx, frontend-v2/src/features/results/utils.ts, frontend-v2/src/features/trial/DoseRow.tsx, frontend-v2/src/index.css
Clean up a couple of 'undexpected any' errors.
Run Prettier across the whole frontend.
=> chore(frontend): clean up type errors and lint

frontend-v2/src/features/projects/Project.tsx
- display project name changes immediately, rather than waiting for an API request to complete.
- refactor project editor form state to remove `values`.
- fix an accessibility bug where tab navigation skips past the project description in edit mode.
=> refactor(frontend): project edit form performance

frontend-v2/src/features/drug/Drug.tsx
- refactor the Drug tab form to use `defaultValues` instead of `values`.
- refactor efficacy experiments to use local form state, where possible.
=> refactor(frontend): Drug form performance

frontend-v2/src/features/drug/Drug.tsx
Remove some redundant code from `submitForm` in the Drug tab.
=> refactor(frontend): clean up Drug tab

.github/workflows/coverage-test.yml, .github/workflows/frontend-coverage.yml, frontend-v2/sonar-project.properties, frontend-v2/vite.config.ts
=> ci(frontend): generate coverage report

frontend-v2/src/features/model/Model.tsx, frontend-v2/src/features/model/PKPDModelTab.tsx, frontend-v2/src/stories/model.mock.ts
Update the Model tab mocks and components to fix failing tests.
=> test(frontend): update the Model tab tests

frontend-v2/src/stories/Model.stories.tsx, frontend-v2/src/stories/Protocols.stories.tsx
Add random delays to mock API responses and refetches in storybook stories.
=> test(frontend): random delays for network mocks

frontend-v2/src/stories/Model.stories.tsx
Add a story that tests changes to the Model species.
=> test(frontend): Model species list

frontend-v2/src/features/model/variables/AdditionalParametersRow.tsx, frontend-v2/src/stories/Model.stories.tsx
Add API mocks and an interaction story for the Secondary Parameters tab.
=> test(frontend): Model secondary parameters

frontend-v2/src/features/model/variables/AdditionalParametersRow.tsx, frontend-v2/src/features/model/variables/VariableRow.tsx, frontend-v2/src/stories/Model.stories.tsx
- add accessible names to Map Variables form inputs.
- add a story and tests for the Map Variables form.
=> test(frontend): map model variables

frontend-v2/src/stories/Simulation.stories.tsx
Add a story that tests the Add Parameter button for simulations.
=> test(frontend): simulation plot parameters

frontend-v2/src/stories/Simulation.stories.tsx, frontend-v2/src/stories/project.mock.ts
Stories and tests for the Add New Plot button.
=> test(frontend): add new plot

frontend-v2/src/features/drug/Drug.tsx, frontend-v2/src/stories/Drug.stories.tsx
Tests and stories for the Drug tab.
=> test(frontend): Drug & Target stories

frontend-v2/.storybook/preview.tsx, frontend-v2/src/components/TableHeader.tsx, frontend-v2/src/features/projects/Projects.tsx, frontend-v2/src/stories/Projects.stories.tsx
Tests and stories for the Projects tab.
=> test(frontend): Projects tab

frontend-v2/src/stories/Projects.stories.tsx
Clear the redux store before each of the Projects stories.
=> test(frontend): test Projects with an empty store

frontend-v2/src/stories/Simulation.stories.tsx, frontend-v2/src/stories/project.mock.ts
Add a story that opens the Customise Plot popup. Update the mock simulation when plots are edited.
=> test(frontend): edit simulation plots

frontend-v2/src/components/HelpButton.tsx, frontend-v2/src/components/TableHeader.tsx, frontend-v2/src/features/main/Sidebar.tsx, frontend-v2/src/features/model/secondary/ThresholdsTable.tsx, frontend-v2/src/features/trial/Doses.tsx
Replace deprecated props that have been replaced by the new slots API.
=> refactor(frontend): Remove deprecated MUI props

frontend-v2/src/features/data/Data.tsx, frontend-v2/src/features/results/Results.tsx
Add summary descriptions of `Data` and `Results` for their Storybook docs pages.
=> test(frontend): Describe Data and Results

frontend-v2/src/stories/Protocols.stories.tsx, frontend-v2/src/stories/protocols.mock.ts
Refactor Trial Design stories to include the data-fetching container in each story and tests.
=> test(frontend): Trial Design data fetching

frontend-v2/src/stories/Model.stories.tsx, frontend-v2/src/stories/project.mock.ts
- update `Model.stories` to include the data-fetching container.
- update tests to wait for data to be fetched.
- clean up mock API state between tests.
=> test(frontend): test Model data-fetching

frontend-v2/src/stories/Model.stories.tsx
Test time intervals, under Model > Secondary Parameters, before and after adding an interval.
=> test(frontend): Model time intervals

frontend-v2/src/stories/Model.stories.tsx, frontend-v2/src/stories/ModelV3.stories.tsx
More robust tests for time intervals, under Secondary Parameters. Test for the start/end time inputs, rather than counting the number of table rows.
=> test(frontend): Model v3 time intervals

frontend-v2/src/stories/ModelV3.stories.tsx, frontend-v2/src/stories/project.v3.mock.ts
A couple of missing API handlers for the version 3 Model tests.
=> test(frontend): missing API handlers

frontend-v2/src/features/model/variables/AdditionalParametersRow.tsx, frontend-v2/src/features/model/variables/MapVariablesTab.tsx, frontend-v2/src/features/model/variables/VariableRow.tsx, frontend-v2/src/stories/Model.stories.tsx, frontend-v2/src/stories/ModelV3.stories.tsx
Add a story for lag times in version 3 models. Fix a bug where selectiing Lag Time doesn't show a Lag Time checkbox for dosing compartments in version 3 models.
=> fix(frontend): Model version 3 lag times

frontend-v2/src/stories/ModelV3.stories.tsx
A story and tests for tumour growth models with the version 3 Model form.
=> test(frontend): tumour growth model for version 3

frontend-v2/src/stories/Protocols.stories.tsx
A quick test to check that the Remove Dose button works.
=> test(frontend): remove a dose from a protocol

frontend-v2/src/features/model/parameters/ParameterRow.tsx, frontend-v2/src/features/model/variables/AdditionalParametersRow.tsx, pkpdapp/pkpdapp/models/combined_model.py
adds `_CeX` where `X` is the effect compartment number to the displayed parameter name
=> bug: distinguish effect compartment parameter names

frontend-v2/src/features/trial/Protocols.tsx
=> bug: if a group has a protocol mapped to a variable that is deleted, no error is shown
