pkpdapp-team/pkpdapp

pkpdapp/pkpdapp/static/assets/css/main.css
pkpdapp/pkpdapp/templates/base.html

The PKPDApp logo now also sticks to the top when scrolling. If it intersects with content a greyish shadow is generated to separate the logo from the background.

Permanent logo

---

pkpdapp/pkpdapp/api/__init__.py
pkpdapp/pkpdapp/api/serializers.py
pkpdapp/pkpdapp/api/views.py
pkpdapp/pkpdapp/settings.py
pkpdapp/pkpdapp/tests/test_api.py
pkpdapp/pkpdapp/urls.py
setup.py

Serializes the dataset model class and nestedly (not a word) serializers the following associated with the dataset within the same class:
- biomarkertypes
- subjects
- protocols
It uses a standard precanned view for the serializer. Using a router, this provides a range of urls in api/datasets/ that allows listing all datasets or via api/datasets/1 giving information about a particular dataset.

REST API for dataset

---

frontend-v2/src/components/DynamicTabs.tsx
frontend-v2/src/components/HelpButton.tsx
frontend-v2/src/features/help/Help.tsx
frontend-v2/src/features/main/Sidebar.tsx
frontend-v2/src/features/main/mainSlice.ts
frontend-v2/src/features/model/Model.tsx
frontend-v2/src/shared/tooltipWrapper.tsx

Added SubPages enum; 
Added selectedSubPage to store; 
Added setting selectedSubPage on subPage change and on page change when Page has DynamicTabs; 
Fixed tooltip being displayed despite page/subpage being changed; 
Added Pointer cursor on tooltip Close icon

Fix tooltips being displayed despite page/subpage change

---

frontend-v2/src/components/TextField.tsx
frontend-v2/src/features/login/login.tsx
frontend-v2/src/features/model/MapVariablesTab.tsx
frontend-v2/src/features/model/VariableRow.tsx
frontend-v2/src/features/simulation/Simulations.tsx
frontend-v2/src/features/trial/Doses.tsx
frontend-v2/src/features/trial/Protocols.tsx

Sorting variables; Lag Time required; Checkboxes error fixes; Simulations layout fixes; Change wrong column name; Fix Login overlay issue

Sorting variables; Lag Time required; Various fixes

---

LICENSE.md
frontend-v2/src/features/login/login.tsx
frontend-v2/src/features/login/loginSlice.ts
pkpdapp/pkpdapp/api/views/login.py
requirements.txt

#327 show login messages from server, remove old logo from login

---

.env.prod
README.md
docker-compose.yml

#328 add tutorial video csv info to readme

---

frontend-v2/src/features/model/MapVariablesTab.tsx
frontend-v2/src/features/model/VariableRow.tsx
frontend-v2/src/features/simulation/SimulationSliderView.tsx
frontend-v2/src/features/simulation/Simulations.tsx
frontend-v2/src/features/trial/Doses.tsx
frontend-v2/src/hooks/useDirty.ts

Fix build warnings in the frontend. Either remove effect hooks, where they can be
replaced, or add the missing dependencies to the effect hook.
See https://react.dev/learn/you-might-not-need-an-effect
Wrap callbacks in `useCallback`, to minimise re-rendering.

refactor: Clean up useEffect build warnings

---

frontend-v2/src/components/DynamicTabs.tsx
frontend-v2/src/components/HelpButton.tsx
frontend-v2/src/features/drug/Drug.tsx
frontend-v2/src/features/login/login.tsx
frontend-v2/src/features/main/Sidebar.tsx
frontend-v2/src/features/main/mainSlice.ts
frontend-v2/src/features/model/MapVariablesTab.tsx
frontend-v2/src/features/model/Model.tsx
frontend-v2/src/features/model/PKPDModelTab.tsx
frontend-v2/src/features/model/ParameterRow.tsx
frontend-v2/src/features/model/VariableRow.tsx
frontend-v2/src/features/projects/Project.tsx
frontend-v2/src/features/projects/UserAccess.tsx
frontend-v2/src/features/simulation/SimulationPlotView.tsx
frontend-v2/src/features/simulation/SimulationSliderView.tsx
frontend-v2/src/features/simulation/Simulations.tsx
frontend-v2/src/features/trial/Doses.tsx
frontend-v2/src/hooks/useDirty.ts
frontend-v2/src/hooks/useInterval.ts
frontend-v2/yarn.lock

- update outdated dependencies.
- refactors to fix build warnings.

Maintenance updates

---

requirements.txt

3.2.24 is a small security patch.

chore(deps): bump Django to 3.2.24

---

requirements.txt

3.2.24 is a small security patch.

chore(deps): bump Django to 3.2.24 (#359)

---

frontend-v2/src/components/HelpButton.tsx

Remove a reference to `open`, which was triggering a 'missing dependency' warning.

refactor: fix HelpButton build warning

---

pkpdapp/pkpdapp/models/myokit_model_mixin.py

- break `create_myokit_simulator` up into smaller methods.
- break `simulate` up into smaller methods.
- add optional `dosing_protocols` to `create_myokit_simulator`. If set, it overrides the default dosing variable protocols.

refactor: optional simulation dosing protocols

---

frontend-v2/src/app/backendApi.ts
frontend-v2/src/features/simulation/SimulationPlotView.tsx
frontend-v2/src/features/simulation/Simulations.tsx
pkpdapp/pkpdapp/api/views/simulate.py
pkpdapp/pkpdapp/models/myokit_model_mixin.py
pkpdapp/pkpdapp/tests/test_views/test_combined_model.py
pkpdapp/pkpdapp/tests/test_views/test_simulate.py
pkpdapp/pkpdapp/tests/utils.py
pkpdapp/schema.yml

Refactor the Myokit model mixin to allow multiple simulations to be run. Each simulation has its own subject group, with subject dosing protocols and dosing events.

feat: allow for multiple Myokit simulations

---

frontend-v2/src/app/backendApi.ts
frontend-v2/src/features/data/Data.tsx
frontend-v2/src/features/simulation/SimulationPlotView.tsx
frontend-v2/src/hooks/useDataset.ts
pkpdapp/pkpdapp/api/serializers/dataset.py
pkpdapp/pkpdapp/utils/data_parser.py
pkpdapp/schema.yml

- add biomarker data to the dataset serialiser.
- add biomarker data to the `useDataset` hook.
- display the dataset as data grids in the Data tab.
- show biomarkers as scatter plots on simulation plots.

feat: plot biomarker data in Simulation tab

---

frontend-v2/src/features/data/LoadData.tsx
frontend-v2/src/features/data/MapDosing.tsx
frontend-v2/src/features/data/MapObservations.tsx
frontend-v2/src/features/data/PreviewData.tsx
frontend-v2/src/features/data/SetUnits.tsx
frontend-v2/src/features/data/Stratification.tsx
frontend-v2/src/features/data/protocolUtils.ts
pkpdapp/pkpdapp/utils/data_parser.py

Better handling of missing unit columns in the CSV.
- When time units are missing, prompt to choose a time unit.
- Change the column headings in the submitted CSV to match headings that are expected by the Python data parser utility.
- Add a preclinical flag to the dosing step during uploads.

refactor: handle missing units in CSV

---

frontend-v2/src/features/simulation/SimulationPlotView.tsx
frontend-v2/src/features/simulation/Simulations.tsx

Add checkboxes to control which subject groups are displayed in the
simulations view.

feat: filter displayed data by groups

---

frontend-v2/src/features/data/LoadDataStepper.tsx
frontend-v2/src/features/projects/Projects.tsx
frontend-v2/src/features/simulation/Simulations.tsx
frontend-v2/src/features/simulation/useSimulation.ts
frontend-v2/src/hooks/useDataset.ts

Replace `useEffect` with event handlers for adding new datasets and finishing uploads. Refetch datasets rather than storing them in a global variable, so that the database is always the source of truth.

refactor: simplify data fetching

---

frontend-v2/src/features/data/LoadData.tsx
frontend-v2/src/features/data/ProtocolDataGrid.tsx
frontend-v2/src/features/data/Stratification.tsx
frontend-v2/src/features/data/SubjectGroupForm.tsx

- Set a default subject group column after uploading a CSV, if none is present.
- List the members of this group in the Stratification view, one row per subject ID.
- Allow users to create groups by editing the group IDs of selected rows in the Stratification view.

refactor: default subject groups

---

pkpdapp/pkpdapp/settings.py
requirements.txt

Install `django-user-visit`, which logs user visits.
You can find the log in the Django admin panel:
http://127.0.0.1:8000/admin/user_visit/uservisit/

feat: user visit logging

---

frontend-v2/src/features/simulation/Simulations.tsx
frontend-v2/src/features/simulation/useExportSimulation.ts

- move the export logic into a useExportSimulation hook.
- include multiple simulations in the CSV file.

refactor: export simulations to CSV file

---

pkpdapp/.coveragerc
pkpdapp/pkpdapp/management/__init__.py
pkpdapp/pkpdapp/management/commands/__init__.py
pkpdapp/pkpdapp/management/commands/test_snapshots.py
pkpdapp/pkpdapp/settings.py
pkpdapp/sonar-project.properties
requirements.txt

Add a custom managment command:
```sh
python manage.py test_snapshots
```
This runs simulations for all combined PKPD models, and saves snapshots of the output logs.
Use it to check for regressions in the model simulations across branches.
```sh
git checkout master
python manage.py test_snapshots
git checkout development
python manage.py test_snapshots
git clean -df
````

feat: snapshot tests for model simulations

---

frontend-v2/src/features/data/CreateDosingProtocols.tsx
frontend-v2/src/features/data/DosingProtocols.tsx
frontend-v2/src/features/data/LoadData.tsx
frontend-v2/src/features/data/LoadDataStepper.tsx
frontend-v2/src/features/data/MapObservations.tsx
frontend-v2/src/features/data/SetUnits.tsx
frontend-v2/src/features/data/normaliseDataHeaders.ts

- missing data columns should be warnings, with info about defaults.
- missing time units should only error when the time unit is undefined.
- a CSV without a header row should error and prevent you from continuing.
- 'Next' should be disabled for errors eg. no time unit set.
- CSV upload errors should be displayed in the UI.

refactor: error handling for data uploads

---

pkpdapp/pkpdapp/models/likelihoods.py

Replace `numpy.random` with a generator, as the legacy `RandomState` can be altered by third-party code.

fix: use secure random generator for likelihoods

---

frontend-v2/package.json
frontend-v2/yarn.lock

Bump TypeScript to 5.4.5. Bump outdated types, including `@types/node`.

deps: upgrade TypeScript and types

---

frontend-v2/src/features/model/PKPDModelTab.tsx
frontend-v2/src/features/projects/Project.tsx

- fix a stray `xs` prop on a Grid container.
- replace `div` with `span` inside table cells.
- closes #400.

fix: fix React errors and warnings

---

frontend-v2/src/features/simulation/Simulations.tsx

Add an `ignore` flag to simulations, so that the response is ignored if the original request is superceded by a new request.

fix: race condition in simulations

---

frontend-v2/src/hooks/useDataset.ts

Make sure that `useDataset` returns the same empty array for groups and biomarkers, in
the case where a project has no datasets. Otherwise, hooks that depend on dataset groups
or biomarkers will be triggered to run on every render.
- fixes #401.

fix: infinite re-renders for projects without datasets

---

Dockerfile

- build the frontend from the Node 20 image.
- copy `yarn.lock` into the image before running `yarn install`.
- freeze the lockfile. Installs that change the Yarn version, or introduce new dependencies, should break the build.

build: Docker updates

---

frontend-v2/src/app/backendApi.ts
frontend-v2/src/features/model/Model.tsx
frontend-v2/src/features/simulation/Simulations.tsx
frontend-v2/src/features/simulation/useExportSimulation.ts
frontend-v2/src/features/simulation/useProtocols.ts
frontend-v2/src/features/simulation/useSimulation.ts
frontend-v2/src/hooks/useDataset.ts
pkpdapp/pkpdapp/api/serializers/project.py
pkpdapp/schema.yml

Calculate the input parameters for simulations, then pass the calculated parameters to hooks as arguments. This should reduce the number of dependencies for the useEffect hook, and reduce or remove redundant API calls that run simulations in the Django app.

refactor: simplify simulation hook parameters

---

frontend-v2/src/features/simulation/Simulations.tsx
frontend-v2/src/features/simulation/useSimulatedVariables.ts
frontend-v2/src/features/simulation/useSimulation.ts
frontend-v2/src/features/simulation/useSimulationInputs.ts
frontend-v2/src/hooks/useDataset.ts

- Wrap `getSimulateInput` and `getVariablesSimulated` in memo-ised custom hooks.`
- run dataset data-fetching requests as soon as the dataset ID is ready, not the dataset itself.

refactor: custom hooks for simulations

---

frontend-v2/src/features/data/Data.tsx
frontend-v2/src/features/data/MapObservations.tsx
pkpdapp/pkpdapp/utils/data_parser.py

When an observation variable is dimensionless, display the units as 'dimensionless', rather than an empty string. Convert 'dimensionless' back to an empty string when we parse the uploaded CSV.

refactor: dimensionless observation units

---

frontend-v2/src/features/data/LoadDataStepper.tsx

Create subject groups before setting dosing compartments or mapping model variables to observations.

refactor: make Stratification the second upload step

---

pkpdapp/pkpdapp/utils/data_parser.py

Convert the CSV column headers to lowercase, then match against lowercase alternates in the Python data parser.

refactor: case-insensitive column headers

---

frontend-v2/src/features/main/Sidebar.tsx
frontend-v2/src/features/simulation/SimulationPlotView.tsx
frontend-v2/src/features/simulation/Simulations.tsx
frontend-v2/src/features/simulation/useProtocols.ts
frontend-v2/src/features/trial/Protocols.tsx
frontend-v2/src/hooks/useDataset.ts
frontend-v2/src/hooks/useSubjectGroups.ts

`useSubjectGroups`, a custom hook that provides a simple API for fetching and refetching project and dataset groups, either individually or combined.

refactor: useSubjectGroups custom hook

---

frontend-v2/src/features/data/MapObservations.tsx
frontend-v2/src/features/data/useObservationRows.ts

When multiple columns are selected as observation columns:
- ignore any observation IDs and units.
- merge the observations into a single Observation column.
- assign a unique Observation ID to each observation column.
- replace the dataset with the merged data. Let the user choose observation units and mapped variables.

feat: support multiple observation columns

---

frontend-v2/src/features/data/LoadData.tsx

Rename the subject ID column to 'ID', if it's called something different.
Only allow one subject ID column. Remove the original column when renaming the ID column.

refactor: normalise subject ID column

---

frontend-v2/src/features/data/PreviewData.tsx
frontend-v2/src/features/data/normaliseDataHeaders.ts

If the Observation column isn't automatically mapped, make sure that the final upload maps the column name to 'Observation'. Otherwise the upload will error with  missing column 'Observation'.

fix(frontend): normalise the Observation column

---

frontend-v2/src/features/data/CreateDosingProtocols.tsx
frontend-v2/src/features/data/DosingProtocols.tsx
frontend-v2/src/features/data/LoadData.tsx
frontend-v2/src/features/data/LoadDataStepper.tsx
frontend-v2/src/features/data/MapObservations.tsx
frontend-v2/src/features/data/SetUnits.tsx
frontend-v2/src/features/data/normaliseDataHeaders.ts

Refactor `validateNormalisedHeaders(headers)` as `validateState(state)`, so that we can generate errors and warnings from the uploaded data. Fixes a small bug where the warning for missing observation units persists, even after you've set observation units.

refactor(frontend): derive errors and warnings from state

---

frontend-v2/package.json
frontend-v2/src/features/simulation/SimulationPlotView.tsx
frontend-v2/yarn.lock

Optimise the build by using `plotly.js-basic-dist-min` instead of `plotly.js`. This reduces Plotly's contribution to the bundle size from ~3.7MB to ~1MB.

build(frontend): use a minimised build of plotly.js

---

frontend-v2/src/App.tsx
frontend-v2/src/components/Checkbox.tsx
frontend-v2/src/components/ConfirmationDialog.tsx
frontend-v2/src/components/DropdownButton.tsx
frontend-v2/src/components/DynamicTabs.tsx
frontend-v2/src/components/FloatField.tsx
frontend-v2/src/components/HelpDialog.tsx
frontend-v2/src/components/IntegerField.tsx
frontend-v2/src/components/SelectField.tsx
frontend-v2/src/components/TextField.tsx
frontend-v2/src/components/Title.tsx
frontend-v2/src/components/UnitField.tsx
frontend-v2/src/features/data/Data.tsx
frontend-v2/src/features/data/SetUnits.tsx
frontend-v2/src/features/help/Help.tsx
frontend-v2/src/features/help/HelpTab.tsx
frontend-v2/src/features/main/MainContent.tsx
frontend-v2/src/features/model/ParametersTab.tsx
frontend-v2/src/features/model/TranslationTab.tsx
frontend-v2/src/features/projects/Projects.tsx
frontend-v2/src/features/simulation/SimulationPlotForm.tsx
frontend-v2/src/features/simulation/Simulations.tsx
frontend-v2/src/hooks/useCustomToast.tsx
frontend-v2/src/index.tsx
frontend-v2/src/shared/tooltipWrapper.tsx

Remove some `import * as` declariations, so that we can tree-shake `react` and `@mui/material` imports.
Remove the React global, where it was still being used.

refactor(frontend): optimise imports

---

frontend-v2/package.json
frontend-v2/yarn.lock

Run `npx vite-bundle-visualizer` or `npx vite-bundle-visualizer -t sunburst` to get a graphical representation of the frontend JS bundles, by module size. Useful for debugging and optimising the build.

build(frontend): add vite-bundle-visualizer

---

frontend-v2/src/features/data/normaliseDataHeaders.ts

`normaliseHeader(field)` overwrites any manual changes to `state.normalisedFields`. It should only be called after uploading a new dataset, not when validating changes to uploaded data.

fix(frontend): normaliseHeader is overwriting manual changes

---

frontend-v2/src/features/data/MapHeaders.tsx
frontend-v2/src/features/data/normaliseDataHeaders.ts

Organise the column types, for uploaded data CSVs, into groups so that the drop down menu is easier to navigate.
https://github.com/pkpdapp-team/pkpdapp/assets/59547/0fab0d8a-0c2a-4b6f-a4a8-de8d38e366b9

feat(frontend): grouped column types menu

---

frontend-v2/src/features/data/LoadDataStepper.tsx
pkpdapp/pkpdapp/utils/data_parser.py

- Add a check for missing time values in the CSV validator.
- Reset the upload stepper state to the first step, after upload errors.

fix(backend): catch missing time values during CSV validation

---

pkpdapp/pkpdapp/utils/data_parser.py

subject id in dataset is stored as an integer in the database, but an uploaded csv could contain non-integer subject ids. In this case we convert the strings into an integer in the validation step

bug: handle data upload case where subject id is a string

---

frontend-v2/src/features/data/DosingProtocols.tsx
frontend-v2/src/features/data/PreviewData.tsx
frontend-v2/src/features/data/SetUnits.tsx
frontend-v2/src/features/data/useObservationRows.ts

Normalise unit headers as Time Unit, Amount Unit, and Observation Unit.

refactor(frontend): normalise unit headers for CSVs

---

frontend-v2/src/features/data/MapObservations.tsx

During the Map Observations step of a data upload, always show the full menu of model variables. Otherwise, it's impossible to change variable after selecting a unit.

refactor(frontend): allow free choice of mapped observation variables

---

frontend-v2/src/features/data/MapObservations.tsx
frontend-v2/src/features/data/useObservationRows.ts

Use a tabbed interface and data grid for the Map Observations step of a data upload. Observations are organised into tabs based on Group ID (set during the Stratification step.)

refactor(frontend): tabbed interface for Map observations

---

frontend-v2/src/features/data/MapObservations.tsx
frontend-v2/src/features/data/PreviewData.tsx
frontend-v2/src/features/data/generateCSV.ts

- standardise row headers for generated CSVs.
- for datasets where the first row is a dosing row, make sure that row has empty observation columns.
- use the first dataset row to determine the row headers for the preview step of an upload.

refactor(frontend): refactor data CSV row headers

---

frontend-v2/src/features/data/LoadDataStepper.tsx

Remove ignored columns from a new dataset before converting it to CSV and uploading it.

fix(frontend): respect Ignore columns for data upload

---

frontend-v2/src/features/data/LoadDataStepper.tsx
frontend-v2/src/features/data/PreviewData.tsx
frontend-v2/src/features/data/normaliseDataHeaders.ts

Ignore any data rows where either 'Censoring' or 'Ignored Observation' is set to 1.

fix(frontend): ignore censored rows

---

frontend-v2/src/features/data/LoadDataStepper.tsx
frontend-v2/src/features/data/PreviewData.tsx
frontend-v2/src/features/data/normaliseDataHeaders.ts

- Fix a bug where the upload only includes ignored columns.
- Make sure every row has the normalised column, when normalising header names.
- Only apply Censoring to dosing rows.
- Only apply MDV/Ignored Observation to observation rows.

fix(frontend): misc. data upload filtering bugs

---

frontend-v2/src/features/data/CreateDosingProtocols.tsx
frontend-v2/src/features/data/DosingProtocols.tsx
frontend-v2/src/features/data/LoadData.tsx
frontend-v2/src/features/data/LoadDataStepper.tsx
frontend-v2/src/features/data/MapDosing.tsx
frontend-v2/src/features/data/MapHeaders.tsx
frontend-v2/src/features/data/MapObservations.tsx
frontend-v2/src/features/data/PreviewData.tsx
frontend-v2/src/features/data/ProtocolDataGrid.tsx
frontend-v2/src/features/data/SetUnits.tsx
frontend-v2/src/features/data/Stratification.tsx
frontend-v2/src/features/data/SubjectGroupForm.tsx
frontend-v2/src/features/data/normaliseDataHeaders.ts
frontend-v2/src/features/data/protocolUtils.ts
frontend-v2/src/features/data/useObservationRows.ts

Refactor normalised headers so that we can get a field's type as `normalisedFields.get(field)`, rather than relying on keeping two arrays in sync with each other.

refactor(frontend): use a Map for normalised headers

---

frontend-v2/src/features/data/CreateDosingProtocols.tsx
frontend-v2/src/features/data/DosingProtocols.tsx
frontend-v2/src/features/data/LoadData.tsx
frontend-v2/src/features/data/LoadDataStepper.tsx
frontend-v2/src/features/data/MapHeaders.tsx
frontend-v2/src/features/data/MapObservations.tsx
frontend-v2/src/features/data/PreviewData.tsx
frontend-v2/src/features/data/SetUnits.tsx
frontend-v2/src/features/data/Stratification.tsx
frontend-v2/src/features/data/normaliseDataHeaders.ts
frontend-v2/src/features/data/useObservationRows.ts

Refactor data upload stepper state so that `state.fields` is a read-only view of `state.normalisedFields.keys()`, rather than maintaining the same state in two separate places. This should fix bugs where fields were missing from `state.fields`, but were present in the CSV data.
Make header normalisation more robust, so that headers are only normalised if there is exactly one header of that type, which can be safely renamed. Normalise columns by renaming the existing column, rather than adding a new column with the normalised name.

refactor(frontend): derive CSV fields from normalised header state

---

pkpdapp/pkpdapp/models/dataset.py
pkpdapp/pkpdapp/tests/test_utils/__init__.py
pkpdapp/pkpdapp/tests/test_utils/test_data_parser.py
pkpdapp/pkpdapp/tests/test_utils/test_monolix_import.py
pkpdapp/pkpdapp/tests/test_utils/test_monolix_parser.py
pkpdapp/pkpdapp/utils/data_parser.py

If EVENT_ID is defined for a dataset, then treat EVENT_ID=0 as an observation row and EVENT_ID=1 or 4 as a dosing row. Ignore Event IDs of 2 or 3 for now.

feat(backend): support EVENT_ID in datasets

---

pkpdapp/pkpdapp/models/dataset.py

bug occurs when evid=0 seen as an event, due to truthyness of `event_id` being confused between `None` and `0`

bug: fix for evid=0 seen as event

---

pkpdapp/pkpdapp/models/myokit_model_mixin.py

The dose start time stored in the Dose table should be absolute, this is necessary to be able to order doses by time, and is the normal form of this data in, for example csv files. This was the original idea when I made this model, but since then we changed the definition so that the dose time was relative to the last dose. This reverts this change so that the dose start time is absolute.
Note that now the UI is inconsistent in the trail design tab. We want to keep this UI because its more convinent for users to enter in dose information in this way, so the upload to the database will have to be updated

bug: dose start time should be absolute

---

frontend-v2/src/features/simulation/SimulationPlotView.tsx

- add an array of colours to the plot view.
- add line and marker colour options to the simulation plots.
- use the same colour for a group's line and its markers.

feat(frontend): custom plot colours

---

frontend-v2/src/features/data/LoadDataStepper.tsx
frontend-v2/src/features/data/normaliseDataHeaders.ts

When MDV is 1 for a row:
- remove the row completely if it is not a dosing row.
- remove the observation entry if it is a dosing row.

fix(frontend): remove ignored observations

---

frontend-v2/src/features/data/normaliseDataHeaders.ts

Show an error if the uploaded CSV has more than one time unit defined in the Time Unit column. At the moment, all uploaded time values must use the same units.

fix(frontend): validate Time Unit column

---

frontend-v2/src/features/data/SetUnits.tsx

Add 'Time Unit' to the stored column headers, after creating a new Time Unit column.

fix(frontend): normalised time units

---

frontend-v2/src/features/data/Stratification.tsx

When stratifying an uploaded dataset, verify that each subject ID only belongs to one group.

refactor(frontend): validate subject group membership

---

frontend-v2/src/features/data/LoadDataStepper.tsx
frontend-v2/src/features/data/Stratification.tsx
frontend-v2/src/features/data/protocolUtils.ts

After uploading or editing a dataset, group the uploaded subjects by dosing protocol. Show an error if any subjects use more than one dosing protocol. Only one protocol per subject is supported at the moment.
After stratifying a dataset, show a warning if a group has more than one dosing regime.

feat(frontend): validate subject dosing protocols

---

frontend-v2/src/features/data/Stratification.tsx
frontend-v2/src/features/data/normaliseDataHeaders.ts

Validate subjects for categorical covariates, checking that covariate values are unique for each subject ID. Show a warning for any columns that don't validate.

refactor(frontend): validate categorical covariates

---

frontend-v2/src/features/data/Stratification.tsx
frontend-v2/src/features/data/normaliseDataHeaders.ts

Move stratification code into a shared function, which returns subject groups for a given data CSV and covariate name.

refactor(frontend): clean up stratification

---

frontend-v2/src/features/data/useObservationRows.ts

When a CSV file has multiple observation columns, and the Observation ID column has been mapped to Ignore, merging the observations columns would create new observsation IDs, but those new IDs are ignored. The fix here is to explicitly set the new columns to Observation and Observation ID, overriding any Ignore settings.

fix(frontend): ignored observation IDs for some CSV files

---

frontend-v2/src/features/data/PreviewData.tsx

The preview step renames columns like Dose, Age, or Weight to Cont Covariate. This causes problems since column names must be unique. Here, continuous covariate columns are not renamed before uploading to the backend.

fix(frontend): don't rename continuous covariate columns

---

pkpdapp/pkpdapp/api/serializers/unit.py
pkpdapp/pkpdapp/api/views/unit.py

Set a default ordering by type and multiplier for the units serializer and for `unit.compatible_units`.

feat(backend): sort units by type and multiplier

---

frontend-v2/src/features/simulation/SimulationPlotView.tsx

Just show the variable name as the y axis label for simulation plots.

fix(frontend): remove group names from y axis labels

---

frontend-v2/src/features/simulation/SimulationPlotView.tsx

Fixes for some bugs with multiple y-axes:
- data for the righthand y-axis was plotted against the lefthand scale.
- generate a unique colour for each plotted variable within a subject group. Previously, colours were only assigned by group.

fix(frontend): fix plots with multiple y-axes

---

frontend-v2/src/features/data/normaliseDataHeaders.ts

`Censoring` ignores observations but not dosing amounts. Remove observation rows that have `Censoring` set. Remove `Observation` from dosing rows that have `Censoring` set.

fix(frontend): censor observations on dosing rows

---

README.md
frontend-v2/package.json
frontend-v2/vite.config.ts
frontend-v2/yarn.lock

Add Google Analytics tracking, using `VITE_APP_GA_ID` to pass in a Google Analytics ID during the build.

feat(frontend): Google Analytics

---

frontend-v2/src/features/data/Stratification.tsx

Add `ID` to the list of CSV columns that can be used to stratify data into groups.

feat(frontend): stratification by subject ID

---

pkpdapp/pkpdapp/models/dataset.py
pkpdapp/pkpdapp/tests/test_utils/test_data_parser.py
pkpdapp/pkpdapp/utils/data_parser.py

Link subjects to protocols via `group.protocols`, not `subject.protocol`. Change the `Dataset` model to group dosing rows by `GROUP_ID`, rather than `SUBJECT_ID`. Generate protocols and doses for rows that have `AMOUNT_VARIABLE` defined, so that each protocol is linked to a dosing compartment in the model.

refactor(backend): allow for multiple subject protocols

---

pkpdapp/pkpdapp/models/dataset.py

Now that protocols are created per group, not per subject, there's no need to dedupe subject protocols.

refactor(backend): remove dataset.merge_protocols

---

frontend-v2/src/features/data/MapDosing.tsx

CSVs can be uploaded with dosing units that aren't listed in the app. This PR validates the 'Amount Unit' column and ignores it if it contains any invalid values. When amount untis are invalid, the user must manually enter dosing units.

refactor(frontend): validate dosing units in uploaded CSVs

---

frontend-v2/src/features/data/SetUnits.tsx

When the Time Unit column contains multiple values, prompt the user to pick a single value from a menu.

refactor(frontend): ignore invalid time units

---

frontend-v2/src/hooks/useSubjectGroups.ts

Simulations implicitly order subject groups by `group.id`. Order subject groups by `group.id` in the frontend so that group labels match their simulations in the Simulations tab.

fix(frontend): order subject groups by group.id

---

frontend-v2/src/features/data/LoadDataStepper.tsx

Editing a dataset errors with 'name cannot be blank' when you save. Make sure that the dataset name is always saved.

fix(frontend): CSV does not save after editing a dataset

---

frontend-v2/src/features/data/CreateDosingProtocols.tsx
frontend-v2/src/features/data/DosingProtocols.tsx
frontend-v2/src/features/data/MapDosing.tsx

When the Amount column is marked as ignored, we want to create dosing protocols based on the Administration ID column (if present), but with dose amounts set to 0.
Also, parse Administration ID as a positive integer, see https://dataset.lixoft.com/description/description-of-column-types-used-to-define-the-dose-regimen/#admidcol

fix(frontend): ignored Amount column

---

frontend-v2/src/features/data/CreateDosingProtocols.tsx

When a CSV data file has no amount or administration ID columns, we want to map dosing compartments to the groups that were created during the Stratification step. Group IDs may not be integers, so can't be parsed with `parseInt`.

fix(frontend): map dosing by group ID

---

frontend-v2/src/features/data/LoadDataStepper.tsx

`.filter` can't be applied to iterators, only to an array generated from an iterator.

fix(frontend): fix array filter during data uploads

---

frontend-v2/src/features/data/CreateDosingProtocols.tsx
frontend-v2/src/features/data/LoadData.tsx
frontend-v2/src/features/data/LoadDataStepper.tsx
frontend-v2/src/features/data/MapDosing.tsx
frontend-v2/src/features/data/Stratification.tsx

When a dataset doesn't contain an administration ID column, generate one during the stratification step. Assign a unique administration ID to each group by default.

refactor(frontend): generate administration IDs during stratification

---

frontend-v2/src/features/main/Sidebar.tsx

Fix highlighting of the selected sidebar tab, which broke in the upgrade to Material v6.

fix(frontend): sidebar nav highlighting

---

frontend-v2/src/app/backendApi.ts
frontend-v2/src/features/model/MapVariablesTab.tsx
frontend-v2/src/features/model/VariableRow.tsx
pkpdapp/pkpdapp/models/combined_model.py
pkpdapp/schema.yml

- add a new `AUC` type to derived variables.
- add a new state equation to the combined model, for the new derived type.
- add a checkbox column to the Map Variables view, which will let you select secondary parameters for a given model variable.
- towards #518.

feat: secondary parameters for models

---

frontend-v2/src/features/simulation/useExportSimulation.ts

Fix missing groups in the simulations CSV export by upgrading to use the `useSubjectGroups` hook.
- fixes #534.

fix(frontend): missing groups in CSV simulation useExportSimulation

---

frontend-v2/src/features/simulation/SimulationPlotView.tsx
frontend-v2/src/features/simulation/Simulations.tsx
frontend-v2/src/features/simulation/useSimulation.ts
frontend-v2/src/features/simulation/useSimulationInputs.ts

- Automatically run simulations for the Results page.
- Automatically add variables with secondary parameters, and their derived variables, to the simulation outputs.

refactor(frontend): include secondary parameters in simulations by default

---

frontend-v2/src/features/model/secondary/ThresholdsTable.tsx
frontend-v2/src/features/results/VariableTable.tsx
frontend-v2/src/features/results/VariableTabs.tsx

- change threshold inputs to uncontrolled, to allow for values like `5e4`.
- display large numbers (> 1e4) as exponentials in the Results tables.
- show units in the Results tables.

refactor(frontend): number formats for secondary parameters

---

frontend-v2/src/App.tsx
frontend-v2/src/app/backendApi.ts
frontend-v2/src/contexts/SimulationContext.ts
frontend-v2/src/features/main/MainContent.tsx
frontend-v2/src/features/main/Sidebar.tsx
frontend-v2/src/features/main/mainSlice.ts
frontend-v2/src/features/model/MapVariablesTab.tsx
frontend-v2/src/features/model/Model.tsx
frontend-v2/src/features/model/VariableRow.tsx
frontend-v2/src/features/model/secondary/SecondaryParameters.tsx
frontend-v2/src/features/model/secondary/ThresholdsTable.tsx
frontend-v2/src/features/model/secondary/TimeIntervalsTable.tsx
frontend-v2/src/features/results/Results.tsx
frontend-v2/src/features/results/VariableTable.tsx
frontend-v2/src/features/results/VariableTabs.tsx
frontend-v2/src/features/simulation/SimulationPlotView.tsx
frontend-v2/src/features/simulation/Simulations.tsx
frontend-v2/src/features/simulation/useSimulation.ts
frontend-v2/src/features/simulation/useSimulationInputs.ts
pkpdapp/pkpdapp/models/combined_model.py
pkpdapp/schema.yml

A demo version of the new secondary parameters feature in the frontend.
- new `AUC` derived variable type in the combined model.
- 'secondary parameters' checkboxes in the Model view. Enable secondary parameters for any concentration variable in the model.
- edit time intervals in the Model view, and set thresholds for variables.
- a Results view showing a table of secondary parameter values for each group and variable.
- a new `SimulationContext` to share simulation outputs across the Simulation and Results views.

feat(frontend): Secondary parameters for model variables

---

frontend-v2/src/App.tsx
frontend-v2/src/features/results/useParameters.tsx

- Remove dummy data for secondary parameters.
- Update `useParameters` for the case where we haven't defined any intervals yet.

refactor(frontend): remove dummy time intervals and thresholds

---

.github/workflows/frontend-build.yml
frontend-v2/package.json
frontend-v2/src/App.test.tsx
frontend-v2/src/features/model/resetToSpeciesDefaults.ts

Run a type check, install, and build for the frontend in the CI pipeline.

build(frontend): test the frontend build in CI

---

frontend-v2/src/features/results/useParameters.tsx
frontend-v2/src/features/results/useUnits.ts
frontend-v2/src/features/results/useVariables.ts

Return empty arrays by default from `useUnits` and `useVariables`.

fix(frontend): set defaults for data-fetching hooks

---

frontend-v2/src/features/model/secondary/ThresholdsTable.tsx
frontend-v2/src/features/model/secondary/TimeIntervalsTable.tsx
frontend-v2/src/features/results/ResultsTab.tsx
frontend-v2/src/features/results/ResultsTable.tsx
frontend-v2/src/features/results/columns.tsx
frontend-v2/src/features/results/useParameters.tsx
frontend-v2/src/features/results/useTableRows.ts
frontend-v2/src/features/results/utils.ts

- Change secondary parameters to take an interval, rather than an array index, in order to match how other table cell parameters are passed around.
- Remove the unit selects from the `ResultsTable` component, so that units are set under Model > Secondary Parameters.
- Only allow one selected time unit for all time intervals.

refactor(frontend): Results table

---

frontend-v2/src/features/results/utils.ts

Add a check for `tMax`, the duration of a simulation, and truncate any time intervals that exceed it.

fix(frontend): truncate time intervals

---

frontend-v2/src/features/model/secondary/TimeIntervalsTable.tsx

Validate that `end_time` is after `start_time` for each time interval.

fix(frontend): validate time intervals

---

frontend-v2/src/features/projects/Project.tsx

Make sure that each radio button in the Projects list has a clickable label.

fix(a11y): missing labels for project radio buttons

---

frontend-v2/src/features/results/columns.tsx
frontend-v2/src/features/results/useParameters.tsx

Two new parameters: the values of each variable at the start and end of each interval.

feat(frontend): add start and end as secondary parameters

---

frontend-v2/src/features/results/useParameters.tsx

FIx another crash that can happen when the current time interval is undefined.

fix(frontend): app crashes when intervals is empty

---

frontend-v2/src/features/results/utils.ts

- Set an error tolerance of 1e-8 and treat smaller values as zero.
- Add exceptions to handle the case where an interval has a duration of zero.

fix(frontend): interpolation errors for secondary parameters

---

frontend-v2/src/features/results/utils.ts

- increase the tolerance to from 1.e-8 to 5.e-7.
- apply the tolerance to `simulation.outputs[variable]`, before applying unit conversion factors.

refactor(frontend): error tolerance in results

---

frontend-v2/src/features/drug/Drug.tsx
frontend-v2/src/features/projects/Project.tsx
frontend-v2/src/features/projects/UserAccess.tsx
frontend-v2/src/features/trial/Doses.tsx

Fix project description not working; Fix doses input getting narrow; Fix unit id being displayed instead of symbol

UI enhancements fixes

---

frontend-v2/src/features/data/DosingProtocols.tsx
frontend-v2/src/features/drug/Drug.tsx
frontend-v2/src/features/main/Sidebar.tsx
frontend-v2/src/features/projects/Project.tsx
frontend-v2/src/features/projects/Projects.tsx
frontend-v2/src/features/results/ResultsTab.tsx
frontend-v2/src/features/simulation/SimulationPlotView.tsx
frontend-v2/src/features/simulation/Simulations.tsx
frontend-v2/src/features/simulation/SimulationsSidePanel.tsx

Simulations sidebar - no layout options selected by default
Simulations sidebar - selecting both layouts deselects both options
Navigation - Fix pkpd version overlap navigation buttons on high scales
Simulation page - fix plots get smaller after each resize/sidebar collapse; Fix height of plots on ultra wide resolutions; Fix simulation Sidebar view for high scales
Simulation page - fix plots box having wrong dimensions on first plot render
Global - Input width and table height adjustments for scales up to 200%
Project page - Disable edit button on shared projects
Simulation page - Add confirmation box to removing plot

Feedback changes and fixes

---

frontend-v2/src/features/simulation/SimulationPlotView.tsx

Leading whitespace in y-axis labels is being displayed as the variable name. This fixes them by trimming the axis names in plot data.

fix(frontend): Missing variable names in plot axis labels

---

frontend-v2/src/features/simulation/SimulationPlotView.tsx

When a plot is a reference plot, the variable name is displayed as `REF` on the y-axis. This fixes that by trimming the `REF ` prefix from y-axis plot names before finding the variable name.

fix(frontend): y-axis REF variables

---

frontend-v2/src/features/simulation/SimulationPlotView.tsx

Add a `variable` property to plot data, then use that when we need to display just the variable name in a plot.

refactor(frontend): add variables to plot data

---

frontend-v2/src/features/drug/Drug.tsx

Restore some deleted code that saves changes to the drug and target form.

fix(frontend): save changes to drug & target

---

frontend-v2/src/features/simulation/SimulationPlotView.tsx
frontend-v2/src/features/simulation/utils.ts

Break up plot axis titles into small utility functions. Plot layout is now composed of a base layout, plot axes, and IC line shapes.

refactor(frontend): plot axis titles 

---

frontend-v2/src/features/data/CreateDosingProtocols.tsx
frontend-v2/src/features/data/DosingProtocols.tsx
frontend-v2/src/features/data/SubjectGroupForm.tsx
frontend-v2/src/features/data/generateCSV.ts

- Add time, additional doses, and interdose interval to dosing rows during uploads.
- Allow users to set dose amounts, units, and repeat doses during an upload, if the uploaded CSV has no dosing rows.
- Append new dosing rows to the end of the CSV, when a CSV has no dosing rows.

refactor(frontend): dosing rows for data uploads

---

frontend-v2/src/features/trial/Doses.tsx
frontend-v2/src/features/trial/Protocols.tsx

Clean up some linter warnings for Trial Design.

style(frontend): lint Trial design

---

frontend-v2/src/features/data/CreateDosingProtocols.tsx
frontend-v2/src/features/data/DosingProtocols.tsx
frontend-v2/src/features/data/MapDosing.tsx
frontend-v2/src/features/data/Stratification.tsx
frontend-v2/src/features/main/Sidebar.tsx

When uploading data without any dosing rows, use the project dosing protocols to determine the default dosing compartments. Previously, an uploaded subject group could only be mapped to a single dosing compartment, even if the model allowed for both IV and SC dosing. With the changes here, subject groups can be dosed from each compartment linked to the model (when an uploaded CSV doesn't have any dosing rows.)
Alter the dosing check in the sidebar so that it only flags up a group if none of that group's protocols have a dose set, rather than checking if any doses are 0.

refactor(frontend) align data upload dosing with Trial Design 

---

frontend-v2/src/features/simulation/SimulationSliderView.tsx

Fix parameter sliders, in simulation plots, so that they can be controlled from the keyboard. Left/right cursor keys for fine control. Shift+left/right cursor keys for coarse control.
- closes #596.

fix(frontend): keyboard controls for parameter sliders

---

frontend-v2/package.json
frontend-v2/src/hooks/useCustomToast.tsx
frontend-v2/yarn.lock

Fixes a bug where the Model tab crashes because `react-toastify` 9 is incompatible with React 19.

build(deps): upgrade react-toastify to v11

---

frontend-v2/src/components/TextField.tsx

A small fix for editable axis titles. Save the default axis title as an empty string, so that it will always be updated whenever we change the displayed variables or units.

fix(frontend): default plot axis titles

---

frontend-v2/src/components/TextField.tsx
frontend-v2/src/features/simulation/SimulationPlotForm.tsx

- use a search field for plot axis labels, so that we can quickly delete the label, if necessary.
- on blur, display the default label if the search field is empty.

fix(frontend): use search inputs for plot axis labels

---

frontend-v2/src/features/model/mmt.js

Replace `IF_EXPRESSION_MODE` with `FUNCTION_MODE` in the MMT syntax highlighter, which should recognise any valid pre-defined function.
https://myokit.readthedocs.io/en/stable/syntax/model.html#pre-defined-functions
Fix a small bug where metadata highlighting doesn't always style the description as a comment.

refactor(frontend): MMT function highlighting

---

frontend-v2/src/features/model/mmt.js

Add `KEYWORD_MODE` for syntax highlighting of MMT `bind` and `label` keywords.

feat(frontend): MMT keyword syntax highlighting

---

frontend-v2/src/features/model/PKPDModelTab.tsx

Remove `Stack` where it was only wrapping a single child.

refactor(frontend): clean up PKPD Model tab layout

---

frontend-v2/src/features/data/MapDosing.tsx

Persist `hasDosingRows` in a ref, so that it doesn't change when an Amount column is automatically added to the stored CSV state.

fix: persist hasDosingRows across renders

---

frontend-v2/src/features/data/LoadData.tsx
frontend-v2/src/features/data/LoadDataStepper.tsx
frontend-v2/src/features/data/MapDosing.tsx
frontend-v2/src/features/data/dataValidation.ts

Refactor data uploads, where the code was validating uploaded dosing rows in a couple of different places. Move that validation into a shared `validateDosingRows` function.
Hoist `hasDosingRows` up into `stepperState.hasDosingRows`, so that it persists when the dosing step unmounts.

refactor(frontend): validate data dosing rows

---

frontend-v2/src/features/data/MapDosing.tsx

Move all the Redux queries into a custom `useApiQueries` hook, mostly for readibility. I'm hoping this makes it easier to see exactly which resources we're fetching from the Django backend.

refactor(frontend): refactor API queries in MapDosing

---

frontend-v2/src/features/data/CreateDosingProtocols.tsx
frontend-v2/src/features/data/MapDosing.tsx

- add an Admin ID column to the `CreateDosingProtocols` table.
- check for missing Admin IDs before generating new dosing rows.
- fix a bug where the Map Dosing step might duplicate editor rows for the same admin ID/dosing compartment, if there are multiple existing protocols for that compartment in the backend. This can happen if you've previously uploaded a dataset, but are now overwriting it with a new dataset.

fix(frontend): create dosing protocols duplicates dosing

---

frontend-v2/src/features/model/VariableRow.tsx
frontend-v2/src/features/model/useEditProtocol.ts

Make the dosing variable checkboxes appear to be more responsive when clicked.
- update checkbox state immediately (in component state), without waiting for API requests to complete.
- small refactor of `removeProtocol` to update the variable form state without waiting for an async action.

refactor(frontend): optimise model variables form

---

frontend-v2/eslint.config.js

Fix a couple of ESLint plugins that broke during the update to v9. ESLint should warn about missing dependencies for React hooks now.

fix (frontend): ESLint config

---

frontend-v2/src/features/model/AdditionalParametersRow.tsx
frontend-v2/src/features/model/Model.tsx
frontend-v2/src/features/model/PKPDModelTab.tsx
frontend-v2/src/features/model/ParametersTab.tsx
frontend-v2/src/features/model/variableUtils.ts

Refactor the Model tab form state to remve complex nested fields. The form state is now a flat object with keys, The form is dirty if any of these keys change:
```js
const formState = {
name: "",
project: 0,
mappings: [],
derived_variables: [],
time_intervals: [],
components: "",
variables: [],
mmt: "",
sbml: "",
time_unit: 0,
is_library_model: false,
species: "M"
}
```
Previously, the form state consisted of two fields, `model` and `project`, both of which were complex objects. Either field would be marked as dirty if its corresponding object changed, which made tracking changes difficult.

refactor(frontend): simplify Model tab form state

---

frontend-v2/src/features/model/Model.tsx
frontend-v2/src/features/model/variableUtils.ts

- add `submitCount` to the Model tab forms. Only submit if the form has not already been submitted. `submitCount` resets whenever the model updates form the backend.
- remove the 1s delay from saves.
- towards #710.

fix(frontend): slow Model variable forms

---

frontend-v2/src/features/simulation/Simulations.tsx

- add `submitCount` to simulations form state. Only save when `submitCount` is 0.
- remove the 1s delay from saves.

refactor(frontend): remove 1s delay from simulation forms

---

frontend-v2/src/features/model/ParameterRow.tsx
frontend-v2/src/features/simulation/Simulations.tsx
frontend-v2/src/features/trial/DoseRow.tsx
frontend-v2/src/features/trial/Doses.tsx

Replace the 1s autosave interval with code that checks `formState.submitCount` to see whether a save is already in progress.
- towards #710.

refactor(frontend): remove 1s autosave delay

---

frontend-v2/src/features/model/Model.tsx
frontend-v2/src/features/model/variableUtils.ts

- use `values` with `useForm`, to reset the form when the model changes.
- use `isSubmitting` to avoid duplicate form submissions.
- manually reset the form after submission, to allow for multiple updates in quick succession.

refactor(frontend): Model variables form performance

---

frontend-v2/src/features/drug/Drug.tsx
frontend-v2/src/features/model/ParameterRow.tsx
frontend-v2/src/features/projects/Project.tsx
frontend-v2/src/features/simulation/SimulationSliderView.tsx
frontend-v2/src/features/simulation/useSimulation.ts
frontend-v2/src/features/simulation/useSimulationInputs.ts
frontend-v2/src/features/trial/DoseRow.tsx
frontend-v2/src/features/trial/Doses.tsx

- fix missing dependency warnings for hooks.
- use `values` with `useForm` to avoid manually resetting form state.

refactor(frontend): code cleanup

---

frontend-v2/src/features/model/AdditionalParametersRow.tsx
frontend-v2/src/features/model/MapVariablesTab.tsx
frontend-v2/src/features/model/Model.tsx

Add an `onChange` handler to `ModelVariablesTab` and use it to handle changes to additional parameters, rather than using `useEffect`.

refactor(frontend): add onChange to ModelVariablesTab

---

frontend-v2/src/features/simulation/useSimulation.ts

Fix a linter error where the dependencies of `useEffect` must be static values.

fix(frontend): complex expression in dependency array

---

frontend-v2/src/features/model/Model.tsx
frontend-v2/src/features/model/variableUtils.ts

Remove `values` from the variable forms in the Model tab. I think this will fix flashes of outdated state, where you'd see a checkbox blink on and off again. Those happen when multiple API updates are triggered in quick succession, and the form state updates after each response. This fixes that by resetting form state before each request, not after.

fix(frontend): flashes of outdated Model variable state

---

frontend-v2/eslint.config.js
frontend-v2/package.json
frontend-v2/src/contexts/SimulationContext.ts
frontend-v2/src/features/data/protocolUtils.ts
frontend-v2/src/shared/contexts/CollapsibleSidebarContext.tsx
frontend-v2/src/shared/contexts/ProjectDescriptionContext.tsx

- run ESLint along with tsc before builds. Fail on errors.
- downgrade 'no-unused-vars' and 'no-explicit-any' to warnings, not errors.
- fix a few unused var warnings.

ci: add eslint to frontend CI checks

---

frontend-v2/src/features/drug/Drug.tsx

- allow the efficacy experiment edit form to close even when the form isn't dirty.
- try to use database IDs as keys for individual table rows, so that editing a row doesn't regenerate the form and lose keyboard focus.
- keep track of the selected row index after edits.
- fixes #735.

refactor(frontend): Drug tab: efficacy experiments

---

frontend-v2/src/features/model/Model.tsx
frontend-v2/src/features/projects/Project.tsx

- fix a bug where changes to new form fields aren't immediately reflected in the model form.
- fix a bug where updating project tags didn't mark the project form as dirty.

fix(frontend): save edits to model and projects

---

frontend-v2/src/components/FloatField.tsx
frontend-v2/src/components/IntegerField.tsx

Fix a bug where `FloatField` and `IntegerField` inputs both submit their values as strings instead of numbers.

fix(frontend): number fields are strings

---

frontend-v2/src/features/model/Model.tsx

Add an error handler to catch case where `updateModel` fails, and reset the Model tab back to its previous state.

refactor(frontend): error handling for model updates

---

frontend-v2/src/features/model/Model.tsx

- reset the PK and PD models when species type changes in the Model tab.
- always save the species fields to the API.

refactor(frontend): reset combined model when species changes

---

frontend-v2/src/features/trial/DoseRow.tsx
frontend-v2/src/features/trial/Doses.tsx

Fix a bug where pressing Add Row once adds multiple doses to a protocol.
- replace `submitCount` with `isSubmitting` to check if the form is currently saving.
- use `reset` to immediately reset the form without waiting for the API.

fix(frontend): multiple submissions for Trial Design: Add Row

---

frontend-v2/src/stories/Protocols.stories.tsx

Reset Protocols stories between runs, so that rerunning the tests doesn't fail because the expected number of table rows has changed.

test(frontend): reset Protocols stories between runs

---

frontend-v2/src/stories/Model.stories.tsx

Model form checkboxes are now disabled, rather than hidden, when there's no selected PK model.

test(frontend): fix Model tests

---

frontend-v2/src/features/projects/Projects.tsx
frontend-v2/src/stories/Drug.stories.tsx
frontend-v2/src/stories/Results.stories.tsx

- remove a stray `console.log`.
- fix a couple of tests that were using `screen` instead of `canvas`.

test(frontend): clean up tests

---

frontend-v2/src/features/data/MapObservations.tsx
frontend-v2/src/features/data/Stratification.tsx
frontend-v2/src/stories/Data.withData.stories.tsx

There's a bug in the Map Observations tab where uploaded data isn't divided into groups if you go straight to that tab without going through the Stratification step. This fixes that bug by passing the uploaded CSV once through the `groupDataRows` function.

fix(frontend): ensure uploaded data has a Group ID column

---

frontend-v2/src/stories/Results.stories.tsx

Reset the RTK query cache between Results tests, to avoid 'Add Table' also adding a table to the default story.

test(frontend): reset RTK query cache for Results

---

frontend-v2/src/stories/Projects.stories.tsx
frontend-v2/src/stories/Protocols.stories.tsx

Reset the RTK query cache between tests for Projects and Protocols.

test(frontend): reset RTK query cache for all beforeEach blocks

---

frontend-v2/src/stories/Data.withData.stories.tsx
frontend-v2/src/stories/Drug.stories.tsx
frontend-v2/src/stories/Model.stories.tsx

Make sure the RTK query cache is clean before each Drug, Model, and Data (edit dataset) test.

test(frontend): reset RTK query cache between tests

---

frontend-v2/src/features/data/MapDosing.tsx
frontend-v2/src/stories/Data.withData.stories.tsx

Fix a bug where the unit selects in Map Dosing are empty if the component renders before any API data has loaded.

fix(frontend): catch empty Map Dosing units

---

frontend-v2/src/stories/Data.noData.stories.tsx

Reset the RTK query cache between tests for Data stories.

test(frontend): reset RTK query cache for Data stories

---

frontend-v2/.storybook/preview.tsx
frontend-v2/src/stories/Data.noData.stories.tsx
frontend-v2/src/stories/Data.withData.stories.tsx
frontend-v2/src/stories/Drug.stories.tsx
frontend-v2/src/stories/Model.stories.tsx
frontend-v2/src/stories/Projects.stories.tsx
frontend-v2/src/stories/Protocols.stories.tsx
frontend-v2/src/stories/Results.stories.tsx
frontend-v2/src/stories/Simulation.stories.tsx

Clean the RTK query cache globally, rather than for individual stories.
Turn off console logs for MSW requests, to reduce noise in CI.

test(frontend): clean RTK query cache globally

---

frontend-v2/src/features/simulation/SimulationsSidePanel.tsx
frontend-v2/src/stories/Simulation.stories.tsx

- refactor simulation sidebar buttons into an `AccordionButton` component.
- add an `aria-expanded` state for screen readers.
- add a test to check the expanded state of a button.
- closes #589.

fix(a11y): simulation sidebar accordion buttons

---

frontend-v2/src/stories/Simulation.stories.tsx
frontend-v2/src/stories/project.mock.ts

Add subject groups to the Simulation stories, with tests for the Groups button in the sidebar.

test(frontend): simulation with subject groups

---

frontend-v2/src/components/DynamicTabs.tsx
frontend-v2/src/features/data/Data.tsx
frontend-v2/src/features/data/MapObservations.tsx
frontend-v2/src/features/data/Stratification.tsx
frontend-v2/src/features/results/Results.tsx
frontend-v2/src/features/trial/Protocols.tsx

Add `selectionFollowsFocus` to all tab lists, so that they can be navigated with the cursor keys.

fix(a11y): support keyboard navigation for tabs

---

frontend-v2/src/features/results/Results.tsx
frontend-v2/src/features/results/useResults.ts
frontend-v2/src/features/trial/Protocols.tsx

Deleting a tab also selects that tab, because tabs are using invalid nested buttons. This works around that by ignoring clicks on the remove button in `handleTabChange`.
Fix some bugs in the way that tab changes were handled by Trial Design.

fix(frontend): delete tab breaks active tab

---

frontend-v2/src/features/data/LoadData.tsx
frontend-v2/src/features/data/MapObservations.tsx
frontend-v2/src/features/data/PreviewData.tsx
frontend-v2/src/features/data/Stratification.tsx

- refactor data-fetching into `useApiQueries` hooks.
- shortcut rendering with a loading message, if `state.data` isn't ready yet (eg. missing required columns.)

refactor(frontend): refactor Upload Data state

---

frontend-v2/src/features/model/variables/AdditionalParametersRow.tsx
frontend-v2/src/stories/Model.stories.tsx

Add a story to test adding a lag time to the dosing compartment. Fix a bug where the lag time checkbox isn't labelled, under Map Variables.

test(frontend): add lag time to model variables

---

frontend-v2/src/features/model/PKPDModelTab.tsx
frontend-v2/src/stories/Model.stories.tsx

- refactor `pd_models_map` as a JS Map.
- add a story that tests the Hill Coefficient checkbox for a variety of PD models.

test(frontend): PD Model Hill Coefficient

---

pkpdapp/pkpdapp/migrations/0034_version_3_pd_models.py
pkpdapp/pkpdapp/migrations/models-v3/PD-Models/Indirect-Effects/DDI/Competitive-inhibition_DDI.mmt
pkpdapp/pkpdapp/migrations/models-v3/PD-Models/Indirect-Effects/DDI/Time-dependent-and-competitive_DDI.mmt
pkpdapp/pkpdapp/migrations/models-v3/PD-Models/Indirect-Effects/DDI/Time-dependent-induction_DDI.mmt
pkpdapp/pkpdapp/migrations/models-v3/PD-Models/Indirect-Effects/DDI/Time-dependent-inhibition_DDI.mmt
pkpdapp/pkpdapp/migrations/models-v3/PD-Models/Indirect-Effects/TGI/Inhibition/TGI_signal-distribution_Emax-kill.mmt
pkpdapp/pkpdapp/migrations/models-v3/PD-Models/Indirect-Effects/TGI/Inhibition/TGI_signal-distribution_econc-prop-kill.mmt

- Change `PKCompartment` to `PDCompartment` for DDI models.
- Change TGI model names to match their filenames.
TODO:

fix(backend): MMT files for v3 PD models

---

frontend-v2/src/features/model/Model.tsx
frontend-v2/src/features/model/parameters/getConstVariables.ts
frontend-v2/src/features/trial/Doses.tsx

Remove unused variables and unused dependencies from React hooks.

refactor: fix linter warnings
